Internacionalizacion de procedimientos
Program-AR/proceds-blockly pull request #10
Opened 2022-03-10 14:13 UTC by dlopezalvas

Related: https://github.com/Program-AR/pilas-bloques/issues/897

2022-03-11 21:04 UTC, asanzo requested changes
Grosa!! Pero al leerlo me dí cuenta de un problema. Ahí aclaro, fijate si te cierra lo que propongo.

2022-03-11 21:04 UTC, asanzo commented on proceds-blockly.js
> +window.initProcedsBlockly = function(useDefaultLanguage = true, customStatementType, initialize = () => {}) {
Hmmmmm eso que propuse (ponerle un parámetro) suponía que no tenía ya parámetros. Ojo que no lo podemos hacer así. Mirá cómo se usa desde otros lugares:

https://github.com/gobstones/gobstones-cli/blob/291a655d62e287b966906fde7d4ebde40a144c25/src/blockly/blocklyCompiler.js#L20

Incluso está en el README del proyecto:

https://github.com/Program-AR/proceds-blockly

O sea, estamos rompiendo la interfaz de `initProcedsBlockly` y eso hace que otros proyectos rompan.

Creo que **no vamos a poder zafar** de cambiar la interfaz (Salvo que lo pongamos al final el valor, pero igual es un poco una mierda). 

Si quisiéramos hacerlo **bien**, deberíamos actualizar blockly y usar la [convención de blockly para internacionalización](https://developers.google.com/blockly/guides/configure/web/translations), que implica cambiar todo el código para usar ese tipo de expresiones: En lugar de hacer `.appendField(Blockly.Msg.PROCEDURES_DEFRETURN_RETURN);`, hacer `.appendField('%{PROCEDURES_DEFRETURN_RETURN}')`, lo cual haría que cuando alguien haga Blockly.setLocale(En) cambie todo a inglés sin tener que volver a correr `initProcedsBlockly`.

PEEEERO

Actualizar Blockly en este proyecto es un mal que no le deseo a nadie por ahora. Está DEMASIADO acoplado a la versión de blockly.

Para mí la forma de resolver esto es:
- [ ] Que exista un objeto `ProcedsBlockly` que sirva de "environment" para no tirar todas las funciones en el espacio global.
- [ ] La función `initProcedsBlockly(...)` y el `PLUS` / `MINUS` / `HAND` deberían estar dentro de ese objeto. (`ProcedsBlockly.init(...)`, `ProcedsBlockly.PLUS`, etc.)
- Eso va a permitir 2 cosas: 1) finalmente que se pueda dividir este monstruo en subtareas y 2) que puedas guardar configuraciones, como si alguien quiere pisar las traducciones o no. Entonces:
- [ ] Sacar todos esos Blockly.Msg.blah de dentro del if a un método `ProcedsBlockly.setDefaultLocale()` (y sacar ese if). O sea, que el init no pise nada por defecto.
- [ ] Cambiar el README donde habla de initProcedsBlockly para cambiarlo por esta nueva forma.
- [ ] Cambiar también el README para contar cómo se agrega un locale. (Asegurándose de definir los Blockly.Msg necesarios antes de llamar al init )
- [ ] Bonus: si queremos mantener retrocompatibilidad, podemos dejar algo así abajo de todo:

```js
window.initProcedsBlockly = function(...args) {
    console.warn('initProcedsBlockly() is deprecated. You should now use ProcedsBlockly.init()')
    ProcedsBlockly.setDefaultLocale()
    ProcedsBlockly.init(...args)
}
```

2022-03-17 19:36 UTC, dlopezalvas commented on proceds-blockly.js
> +window.initProcedsBlockly = function(useDefaultLanguage = true, customStatementType, initialize = () => {}) {
Sigue quedando monstruoso el init por ahora (? No quise meter mucha mano para no romper cosas, ¿aprovechamos a dividir más en subtareas en este pr?

2022-03-18 19:11 UTC, asanzo approved these changes
Bravo @dlopezalvas !!!! :clap: :clap: .

Hice un comentario con algo para que pruebes si arregla el error. (el `window`)

2022-03-18 19:11 UTC, asanzo commented on README.md
> +    // or ProcedsBlockly.init("Statement"); for custom statement type configurations
Yo creo que agregaria una línea antes en este ejemplo:
`ProcedsBlockly.setDefacultLocale() // if no translation was loaded previously`

2022-03-18 19:11 UTC, asanzo commented on proceds-blockly.js
> +const ProcedsBlockly = {
Tengo la ligera sospecha de que la razón por la que lo otro estalla está acá.
Acá hay que poner:

```suggestion
window.ProcedsBlockly = {
```

Explicación acá:

https://eqsash.com/articles/chem-otlichaetsya-obyavlenie-peremennyh-v-javascript-chto-vybrat-window-var-let-const?l=en

Estamos usando este proyecto esperando justamente que agregue al espacio global el objeto ProcedsBlockly.

2022-03-22 17:40 UTC, asanzo approved these changes

2022-03-22 17:51 UTC, asanzo commented
@dlopezalvas está genial esto. Dado que estamos por deprecar una forma de usarlo (aunque todavía sigue funcionando) yo subiría una version `minor` (o sea pasar de 1.0.1 a 1.1.0, en lugar de 1.0.2). 
Si alguna vez matamos el método `initProcedsBlockly` del todo, hay que subir la major y pasar a 2.0.0, pero por ahora no me parece necesario.

Que @tfloxolodeiro o @ezequielPereyra hagan el merge si no tienen comment ;)

(estoy intentando que al menos 2 de nosotres hagamos review por cada PR, al menos mientras estamos aprendiendo y conociendo los proyectos).

2022-03-23 14:53 UTC, tfloxolodeiro approved these changes

2022-03-25 05:20 UTC, merged